### ISSUE TITLE
Add Kafka serde generator

### ISSUE THREAD

**Issue by kalmanb** [movio/movio-apidoc-generator#19]
_From @echojc on March 2, 2016 4:44_

Adds generators for Kafka's `Serializer` and `Deserializer` interfaces, which can be used with the producer and consumer config's `key.serializer`, `key.deserializer`, `value.serializer` and `value.deserializer` configs.

This is a simple wrapper around the Play JSON serdes.

Tested against `"org.apache.kafka" % "kafka-clients" % "0.9.0.1"`.

_Copied from original issue: movio/apidoc-generator-old/pull/19_

**Comment by kalmanb** [comment]
Two suggestions: 
We currently versioning kafka and play generators in thier names. Not manditiory but might be useful in the future.
You might want some high level tests to help others contrib, eg AdvancedCaseClassesSpec
Happy to merge though.

**Comment by kalmanb** [comment]
_From @echojc on March 11, 2016 0:6_

I'd prefer not to check the generated code because it makes adding changes harder (and doesn't really guarantee correctness anyway). I think a better way is to randomly generate entities and set up round trip tests using ScalaCheck or something similar. That way, we're testing the behaviour of the output, not the textual representation of it.

That requires a way to generate `Arbitrary`s though. We could build a generator for that, or maybe use https://github.com/alexarchambault/scalacheck-shapeless? This was the library I mentioned in my shapeless talk which gives you arbitrary case classes using the technique I talked about.

Thoughts?

**Comment by kalmanb** [comment]
Happy for you do to either, up to you. The simple string comparision has worked well for me so far. I often start making changes with https://github.com/movio/apidoc-generator-reference-lib and https://github.com/movio/apidoc-generator-reference-svc. I add the functionality that I'm looking for. Then I copy the changes over to the generator. The tests allow me to refactor safely.

**Comment by kalmanb** [comment]
_From @echojc on March 16, 2016 4:31_

Cross reference movio/generator-apidoc-libs#6

I've added generators for ScalaCheck's Arbitrary and for round trip tests for both Samza and Kafka 0.9 serdes. This means any library that generates one of these serdes will have a generated test inside it that can check whether the serde works as expected.

**Comment by kalmanb** [comment]
@echojc this is done yeah?

**Comment by echojc** [comment]
@kalmanb I think so, the old PR is marked as merged.
