### ISSUE TITLE
Added field names object to Play2Json

### ISSUE THREAD

**Issue by kalmanb** [movio/movio-apidoc-generator#21]
_From @jamesk on March 11, 2016 0:2_

Not sure if other places that should be updated and tests?

_Copied from original issue: movio/apidoc-generator-old/pull/22_

**Comment by kalmanb** [comment]
_From @jamesk on March 11, 2016 0:3_

Wondered also whether the `originalName` was sanitised already, e.g. no quotes or other special chars

**Comment by kalmanb** [comment]
@jamesk was this done?

**Comment by jamesk** [comment]
It's in the generator now but now sure if the question about `originalName` being sanitised was answered

**Comment by kalmanb** [comment]
Closing for now
